name: Codacy Coverage Reporter

on:
  workflow_run:
    workflows:
      - Build and Test
    types:
      - completed
  workflow_dispatch:

permissions:
  contents: read

jobs:
  report-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Download coverage report
        uses: actions/download-artifact@v4
        with:
          name: coverage-report
          github-token: ${{ secrets.API_GITHUB }}
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1.3.0
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage.cobertura.xml