name: Codacy Coverage Reporter

on:
  workflow_run:
    workflows:
      - Build and Test
    types:
      - completed

jobs:
  report-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Download coverage report
        uses: actions/download-artifact@v3
        with:
          name: coverage-report
          path: ./coverage
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1.3.0
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: ./coverage/coverage.cobertura.xml